spring:
  application:
    name: springairaglab
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      file: compose.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/springairaglabdb
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key-to-pass-startup-check}
      enabled: false
      embedding: 
        enabled: false

server:
  port: 8080
